brew 'ag'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'colordiff'
brew 'coreutils'
brew 'diffutils'
brew 'findutils'
brew 'gh'
brew 'git'
brew 'gnu-sed'
brew 'grep'
brew 'gzip'
brew 'hugo'
brew 'inetutils'
brew 'jq'
brew 'less'
brew 'neovim'
brew 'parquet-tools'
brew 'python'
brew 'tmux'
brew 'vim'

cask '1password'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'microsoft-teams'
cask 'rectangle'
cask 'skitch'
cask 'slack'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'zoom'

mas 'Bear', id: 1091189122
