brew 'ag'
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'colordiff'
brew 'coreutils'
brew 'diffutils'
brew 'duckdb'
brew 'ffmpeg'
brew 'findutils'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'gnu-sed'
brew 'granted'
brew 'grep'
brew 'gzip'
brew 'helix'
brew 'hugo'
brew 'imagemagick'
brew 'inetutils'
brew 'jq'
brew 'less'
brew 'neovim'
brew 'parallel'
brew 'python'
brew 'python-yq'
brew 'tmux'
brew 'vim'

cask '1password'
cask '1password-cli'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
cask 'gpg-suite-no-mail'
cask 'karabiner-elements'
cask 'kitty'
cask 'lulu'
cask 'microsoft-teams'
cask 'rectangle'
cask 'skitch'
cask 'slack'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'wireshark'
cask 'zoom'

mas 'Bear', id: 1091189122
mas 'Tailscale', id: 1475387142

tap 'common-fate/granted'
