theme = "base16_transparent"

[editor]
rulers = [90,140]
bufferline = "always"
text-width = 90
auto-pairs = false
auto-format = false
insert-final-newline = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[keys.normal]
X = "extend_line_above"
