" Vim is based on Vi. Setting `nocompatible` switches from the default Vi-compatibility
" mode and enables useful Vim functionality. This configuration option turns out not to be
" necessary for the file named '~/.vimrc', because Vim automatically enters nocompatible
" mode if that file is present. But we're including it here just in case this config file
" is loaded some other way (e.g. saved as `foo`, and then Vim started with `vim -u foo`).
set nocompatible

" Set up plugins first so anything in this file will overwrite the stuff set by a plugin.
source ~/.vim/plugins.vim

" Set the settings needed for vim to look alright when using kitty
source ~/.vim/kitty.vim

" Turn on syntax highlighting.
syntax on

" Set the default output encoding as displayed in the terminal
" See: https://stackoverflow.com/a/16507826
set encoding=utf-8

" Disable the default Vim startup message.
set shortmess+=I

" Use the system clipboard for the unnamed register.
set clipboard=unnamed

set history=200

" Set my leader value
let mapleader = "-"

" Use ag as the default :grep program
set grepprg=ag\ --vimgrep\ $*

" Create a new Ag command that will automatically open the quickfix window if there are
" any matches. For more info, see:
" https://gist.github.com/romainl/56f0c28ef953ffc157f36cc495947ab3
function! Ag(...)
   return system(join([&grepprg] + [expandcmd(join(a:000, ' '))], ' '))
endfunction

command! -nargs=+ -complete=file_in_path -bar Ag  cgetexpr Ag(<f-args>)
command! -nargs=+ -complete=file_in_path -bar Lag lgetexpr Ag(<f-args>)

augroup quickfix
   autocmd!
   autocmd QuickFixCmdPost cgetexpr cwindow
   autocmd QuickFixCmdPost lgetexpr lwindow
augroup END

" Show trailing whitespace
" - non-color terminals: reverse the text and background "colors"
" - color terminals and GUI: set the background to red
highlight ExtraWhitespace term=reverse ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Word wrap columns
set textwidth=90
set colorcolumn=90,140

" Remove trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Indentation settings: http://vim.wikia.com/wiki/Indenting_source_code
" NOTE: using larger tabstop to see when there are tabs that shouldn't exist
set expandtab
set tabstop=8
set shiftwidth=3
set softtabstop=3
set autoindent
set smartindent
set ignorecase

" Show invisible characters
set list
set listchars=
set listchars+=space:·
set listchars+=tab:»»

" Show line numbers.
set number

" Always show the status line at the bottom, even if you only have one window open.
set laststatus=2

" The backspace key has slightly unintuitive behavior by default. For example, by default,
" you can't backspace before the insertion point set with 'i'. This configuration makes
" backspace behave more reasonably, in that you can backspace over anything.
set backspace=indent,eol,start

" By default, Vim doesn't let you hide a buffer (i.e. have a buffer that isn't shown in
" any window) that has unsaved changes. This is to prevent you from forgetting about
" unsaved changes and then quitting e.g. via `:qa!`. We find hidden buffers helpful enough
" to disable this protection. See `:help hidden` for more information on this.
set hidden

" This setting makes search case-insensitive when all characters in the string being
" searched are lowercase. However, the search becomes case-sensitive if it contains any
" capital letters. This makes searching more convenient.
set ignorecase
set smartcase

" Enable searching as you type, rather than waiting till you press enter.
set incsearch

" Highlight all search matches
set hlsearch

" Keep the cursor centered when going through search results.
nnoremap n nzzzv
nnoremap N Nzzzv

" Allow me to edit and reload my vimrc on demand
nnoremap <leader>ev :split $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Unbind some useless/annoying default key bindings.
nmap Q <Nop> " 'Q' in normal mode enters Ex mode. You almost never want this.

" Disable audible bell because it's annoying.
set noerrorbells visualbell t_vb=

" The new window will appear to the right when I do a vertical split.
set splitright

" Enable mouse support. You should avoid relying on this too much, but it can sometimes be
" convenient.
set mouse+=a

" This setting is the length of time Vim waits after you stop typing before it triggers
" the plugins governed by updatetime. This defaults to 4000 milliseconds which is way too
" long if you want your plugins to feel responsive.
set updatetime=250

" Settings for git commit messages
augroup commitMessages
   autocmd!
   autocmd FileType gitcommit set textwidth=90
   autocmd FileType gitcommit set colorcolumn+=72
augroup END

" Easily jump to the beginning and the end of the line
nnoremap H ^
nnoremap L $

" Create shortcuts for moving between buffers.
nnoremap <silent> [b :bprevious<CR>
nnoremap <silent> ]b :bnext<CR>
nnoremap <silent> [B :bprevious<CR>
nnoremap <silent> ]B :bnext<CR>

